server:
  error:
    include-stacktrace: ON_PARAM
    
spring:
  datasource:
    #url: jdbc:mysql://200.128.9.179:3306/academia?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true 
    #username: remoto
    #password: remoto
    url: jdbc:mysql://localhost:3306/academia?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true 
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update   