spring:
  datasource:
    url: jdbc:mysql://200.128.9.179:3306/academia?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true 
    username: remoto
    password: remoto
  jpa:
    hibernate:
      ddl-auto: update   